name: auto-tests-mlops

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Show login info
      run: |
        echo "Hello! My name is ${{ secrets.MY_LOGIN }}. My password is ${{ secrets.MY_PASSWORD }}."

  lint:
    runs-on: ubuntu-latest
    needs: greeting
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - run: pip install flake8
    - run: flake8 src/ tests/

  unit-tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - run: |
        pip install -r requirements.txt
        pip install pytest
    - run: pytest tests/unit

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - run: |
        pip install -r requirements.txt
        pip install pytest
    - run: pytest tests/integration
